In [112]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, ElasticNetCV, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
import pickle

In [33]:
df = pd.read_csv('Admission_Prediction.csv')

In [34]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [35]:
pf = ProfileReport(df)

In [36]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [41]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [43]:
df['TOEFL Score'] = df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [46]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [48]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.103952     6.051338           1.128802    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  309.000000   103.000000           2.000000    2.500000   
50%    250.500000  316.558763   107.000000           3.000000    3.500000   
75%    375.250000  324.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [50]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [57]:
df.drop(columns=['Serial No.'],inplace=True)

KeyError: "['Serial No.'] not found in axis"

In [58]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [60]:
y = df['Chance of Admit']

In [62]:
x = df.drop(columns=['Chance of Admit'])

In [64]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [66]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [129]:
scaler = StandardScaler()

In [138]:
x = x.values
arr = scaler.fit_transform(x)

In [73]:
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [76]:
df1 = pd.DataFrame(arr)

In [80]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   4.350520e-15  9.419132e-16  5.608847e-16  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.394225e+00 -2.512331e+00 -1.881441e+00 -2.397950e+00 -2.686789e+00   
25%   -6.814090e-01 -6.927310e-01 -9.946589e-01 -8.828175e-01 -5.235128e-01   
50%    5.124333e-15 -3.105811e-02 -1.078766e-01  1.272712e-01  1.730621e-02   
75%    6.708143e-01  7.960330e-01  7.789057e-01  6.323155e-01  5.581253e-01   
max    2.113186e+00  2.119379e+00  1.665688e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [82]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [88]:
arr.shape

(500, 7)

In [89]:
vif_df = pd.DataFrame()

In [96]:
vif_df['vif'] = [variance_inflation_factor(arr, i) for i in range(arr.shape[1])]

In [97]:
vif_df['features'] = x.columns

In [99]:
vif_df

features       vif
0          GRE Score  4.153268
1        TOEFL Score  3.792866
2  University Rating  2.508768
3                SOP  2.775750
4                LOR  2.037308
5               CGPA  4.651670
6           Research  1.459311

In [171]:
x_train, x_test, y_train, y_test = train_test_split(arr, y, test_size=0.25, random_state = 350)

In [105]:
x_train

array([[-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [-1.67303946e+00, -1.02356739e+00,  7.78905651e-01, ...,
         1.09894429e+00, -1.46711143e+00,  8.86405260e-01],
       [-4.10964364e-01,  1.34360100e-01, -1.07876604e-01, ...,
        -5.23512832e-01, -7.68609886e-02, -1.12815215e+00],
       ...,
       [ 4.90517846e-01,  1.29228759e+00,  1.66568791e+00, ...,
         1.09894429e+00,  1.29683885e+00,  8.86405260e-01],
       [-1.67303946e+00, -1.68524024e+00,  3.93810431e-16, ...,
        -5.23512832e-01, -2.26154025e+00, -1.12815215e+00],
       [ 1.75259294e+00,  1.95396044e+00,  1.66568791e+00, ...,
         1.73062093e-02,  2.02506527e+00,  8.86405260e-01]])

In [107]:
lr = LinearRegression()

In [109]:
lr.fit(x_train, y_train)

LinearRegression()

In [148]:
pickle.dump(lr,open('addmission_lr_model.pickle', 'wb'))

In [143]:
test1 = scaler.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])
test1

array([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

In [142]:
lr.predict(test1)

array([0.95377928])

In [135]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [149]:
model = pickle.load(open('addmission_lr_model.pickle', 'rb'))

In [151]:
model.predict(test1)

array([0.95377928])

In [156]:
lr.score(x_test, y_test) 

0.7476466381844958

In [154]:
x_test

array([[-3.20816143e-01,  2.99778313e-01, -1.07876604e-01,
         6.32315491e-01,  1.73062093e-02,  7.01017234e-01,
        -1.12815215e+00],
       [-3.20816143e-01, -8.58149178e-01, -1.07876604e-01,
        -1.38786180e+00, -5.23512832e-01, -5.07176601e-01,
        -1.12815215e+00],
       [ 6.70814288e-01,  4.65196526e-01, -1.07876604e-01,
         1.27271169e-01, -5.23512832e-01,  1.06513044e+00,
         8.86405260e-01],
       [ 2.02303760e+00,  1.45770580e+00,  7.78905651e-01,
         6.32315491e-01,  1.73062093e-02,  2.02506527e+00,
         8.86405260e-01],
       [ 1.29924962e-01, -1.96476326e-01, -1.07876604e-01,
        -1.38786180e+00, -5.23512832e-01,  1.21746217e-01,
        -1.12815215e+00],
       [-4.10964364e-01, -3.61894539e-01, -9.94658860e-01,
        -1.38786180e+00, -1.06433187e+00, -2.09265793e-01,
        -1.12815215e+00],
       [ 1.29924962e-01,  2.99778313e-01, -1.07876604e-01,
         1.27271169e-01,  5.58125251e-01,  1.06513044e+00,
         8.8640526

In [158]:
y_test

289    0.79
167    0.64
371    0.89
148    0.96
391    0.71
       ... 
106    0.87
9      0.45
323    0.62
417    0.52
238    0.70
Name: Chance of Admit, Length: 125, dtype: float64

In [162]:
#A function to create adjusted R-squared by Sudhanshu Kumar
def adj_r2(x,y):
    r2 = lr.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [172]:
adj_r2(x_test, y_test)

0.8121980270265747